name: Daily Build

on:
    schedule:
        - cron: '0 6 * * *'

permissions:
    contents: read

jobs:
    nightly:
        if: github.repository == 'primefaces/primevue' && github.ref == 'refs/heads/master'
        runs-on: ubuntu-latest
        name: Node ${{ matrix.node-version }}

        strategy:
            matrix:
                node-version: [20, 22, 24]

        steps:
            - name: Checkout repository
              uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

            - name: Install pnpm
              uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
              with:
                  version: 9.6.0

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'

            - name: Build
              run: |
                  pnpm run setup
                  pnpm run build:lib
